name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 
        architecture: 'x64' 
     - name: Cache pip
       uses: actions/cache@v1
        with:
            # This path is specific to Ubuntu
            path: ~/.cache/pip
            # Look to see if there is a cache hit for the corresponding requirements file
            key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
            restore-keys: |
                ${{ runner.os }}-pip-
                ${{ runner.os }}-
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - run: |
        pip install flake8
        flake8 --select=E1,E2
